services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_APP=run.py      
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: qmsh
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: